
all:
	cd examen-ambas-mitades ; cd parte-escrita; make; cd .. ; cd parte-ordenador; make ; cd .. ; cd .. ; cd examen-segunda-mitad ; cd parte-escrita; make; cd .. ; cd parte-ordenador; make ; cd .. ; cd ..
